# Project Config
[project]
project_id = "atwcovxfbxxdrecjsfyy"

[api]
url = "https://atwcovxfbxxdrecjsfyy.supabase.co"

[auth]
# Get this from your project dashboard
token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0d2NvdnhmYnh4ZHJlY2pzZnl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDY5ODAsImV4cCI6MjA2NDY4Mjk4MH0.5pOsDnI5HrgBDvG8m7II_4jQ4btuSfQQrqPrj2gK0tI" 